name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        run: |
          choco install openjdk
          java -version
      - name: Download FlexSDK 4.16.1 on AIR 32.0
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/mxfuqz4gkiqh0zh71jpwt/Flex_4.16.1_AIR_32.0.zip?rlkey=r2pk9ha9m0kmdh1yox4qmq1oq&st=f4k5kao8&dl=1" -OutFile "$HOME\Flex_4.16.1_AIR_32.0.zip"
          Expand-Archive -Path "$HOME\Flex_4.16.1_AIR_32.0.zip" -DestinationPath "$HOME\Flex_4.16.1_AIR_32.0"
      - name: Download fdbuild.exe
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/r13v8uvjk7bbt1sfzy9tq/fdbuild.exe?rlkey=3drlcoylqa74b7oa3lvmpyyhf&st=o3t3ddt9&dl=1" -OutFile "$HOME\fdbuild.exe"
      - name: Generate .xml configuration
        run: |
          Write-Output "Repo path: $env:GITHUB_WORKSPACE"
          Write-Output "FlexSDK path: $HOME\Flex_4.16.1_AIR_32.0"
          Get-ChildItem -Path "$HOME\Flex_4.16.1_AIR_32.0\lib"
          & "$HOME\fdbuild.exe" $env:GITHUB_WORKSPACE\QoLAF.as3proj -version "4.16.1" -compiler $HOME\Flex_4.16.1_AIR_32.0
